### ISSUE TITLE
Can be run in local ghostfolio?

### ISSUE THREAD

**Issue by zozito** [agusalex/ghostfolio-sync#10]
Hi team,

I did all the steps, creating an flex query on Interactive Brokers and enabled the Flex Web Service

I put all the information as your instructions and I'm getting this error:

```
[2023-09-06 10:24:10] Starting ghostfolio-sync Docker...
[2023-09-06 10:24:10] Crontab Not Present running one time now
Traceback (most recent call last):
  File "/usr/app/src/main.py", line 11, in <module>
    ibkr_tokens = os.environ.get("IBKR_TOKEN").split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```

Can you help me understand what i'm doing wrong?

Thank you

**Comment by alishafique1** [comment]
I am having the same issue with same logs


Traceback (most recent call last):
  File "/usr/app/src/main.py", line 11, in <module>
    ibkr_tokens = os.environ.get("IBKR_TOKEN").split(",")
AttributeError: 'NoneType' object has no attribute 'split'
[2023-09-07 15:16:34] Starting ghostfolio-sync Docker...
[2023-09-07 15:16:34] Crontab Not Present running one time now

This is on Unraid 

One more issue is Ghost_token is the auth token for access but we are not defining which account the sync should happen to after the sync occurs. How do we define that?

**Comment by snhuber** [comment]
There is a mistake in the documentation. You need to fire the docker run command with _ in the parameters:

IBKR_TOKEN not IBKR-TOKEN and same for IBKR_QUERY

**Comment by zozito** [comment]
Hi @snhuber after correct the parameters I got a new error:

```
[2023-09-15 09:55:45] Starting ghostfolio-sync Docker...
[2023-09-15 09:55:45] Crontab Not Present running one time now
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 115, in parse_data_element
[2023-09-15 09:55:47] Starting sync
    attrs = dict(
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 116, in <genexpr>
    parse_element_attr(Class, k, v)
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 156, in parse_element_attr
    Type = Class.__annotations__[name]
KeyError: 'figi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/app/src/main.py", line 22, in <module>
    ghost.sync_ibkr()
  File "/usr/app/src/SyncIBKR.py", line 71, in sync_ibkr
[2023-09-15 09:55:47] Fetching Query
    query: FlexQueryResponse = parser.parse(response)
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 53, in parse
    parsed = parse_element(root)
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 85, in parse_element
    return parse_data_element(elem)
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 125, in parse_data_element
    contained_elements = {child.tag: parse_element(child) for child in elem}
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 125, in <dictcomp>
    contained_elements = {child.tag: parse_element(child) for child in elem}
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 80, in parse_element
    return parse_element_container(elem)
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 101, in parse_element_container
[2023-09-15 09:55:47] Parsing Query
    instances = tuple(parse_data_element(child) for child in elem)
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 101, in <genexpr>
    instances = tuple(parse_data_element(child) for child in elem)
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 125, in parse_data_element
    contained_elements = {child.tag: parse_element(child) for child in elem}
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 125, in <dictcomp>
    contained_elements = {child.tag: parse_element(child) for child in elem}
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 83, in parse_element
    return parse_element_container(elem)
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 101, in parse_element_container
    instances = tuple(parse_data_element(child) for child in elem)
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 101, in <genexpr>
    instances = tuple(parse_data_element(child) for child in elem)
  File "/usr/local/lib/python3.9/site-packages/ibflex/parser.py", line 121, in parse_data_element
    raise FlexParserError(msg)
ibflex.parser.FlexParserError: OpenPosition has no attribute 'figi'
```
Can you help me?

Thank you

**Comment by snhuber** [comment]
You can just deselect the column in the IB Flex attributes for open positions, trades, and cash transactions.

**Comment by zozito** [comment]
I disabled but the error are the same

**Comment by snhuber** [comment]
Same error means you have not disabled it in the Flex Query. Just check again and be sure to save two times. The attributes and the query itself on IB.

**Comment by paulsp94** [comment]
> There is a mistake in the documentation. You need to fire the docker run command with _ in the parameters:
> 
> IBKR_TOKEN not IBKR-TOKEN and same for IBKR_QUERY

@agusalex opened a PR #12

**Comment by agusalex** [comment]
> I'm almost there...
> 
> In fact I forgot to disable one Flex attributes. Now I'm getting this error
> 
> ```
> [2023-09-15 15:25:22] Starting ghostfolio-sync Docker...
> [2023-09-15 15:25:22] Crontab Not Present running one time now
> [2023-09-15 15:25:24] Starting sync
> [2023-09-15 15:25:24] Fetching Query
> [2023-09-15 15:25:24] Parsing Query
> [2023-09-15 15:25:24] No connection adapters were found for '192.168.1.172:3334/api/v1/account'
> [2023-09-15 15:25:24] No connection adapters were found for '192.168.1.172:3334/api/v1/account'
> [2023-09-15 15:25:24] Failed to retrieve account ID closing now
> [2023-09-15 15:25:24] End sync
> ```
> 
> I can retrive the KEY using the example https://GHOST_HOST/api/v1/auth/anonymous/KEY and replece the AuthToken in GHOST_TOKEN variable.
> 
> I'm doing something wrong?
> 
> Thank you

Did you solve the issue? Can we close this now?

**Comment by zozito** [comment]
I'm sorry about my delay,

Yes you can close this.

Thank you
